/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductInput = IDL.Record({
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const Rating = IDL.Nat;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'rating' : Rating,
});
export const ProductReviews = IDL.Record({
  'reviews' : IDL.Vec(Review),
  'averageRating' : IDL.Opt(Rating),
  'reviewCount' : IDL.Nat,
});
export const RegistrationInput = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ReviewInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Text,
  'rating' : Rating,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'adminCheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProductAverageRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ProductId, IDL.Opt(Rating)))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductRatingSummary' : IDL.Func(
      [ProductId],
      [IDL.Opt(ProductReviews)],
      ['query'],
    ),
  'getProductReviewCount' : IDL.Func([ProductId], [IDL.Nat], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([ProductId], [ProductReviews], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([RegistrationInput], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([ProductId, ReviewInput], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductInput = IDL.Record({
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const Rating = IDL.Nat;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'rating' : Rating,
  });
  const ProductReviews = IDL.Record({
    'reviews' : IDL.Vec(Review),
    'averageRating' : IDL.Opt(Rating),
    'reviewCount' : IDL.Nat,
  });
  const RegistrationInput = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const ReviewInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Text,
    'rating' : Rating,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'adminCheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProductAverageRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ProductId, IDL.Opt(Rating)))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductRatingSummary' : IDL.Func(
        [ProductId],
        [IDL.Opt(ProductReviews)],
        ['query'],
      ),
    'getProductReviewCount' : IDL.Func([ProductId], [IDL.Nat], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviews' : IDL.Func([ProductId], [ProductReviews], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([RegistrationInput], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([ProductId, ReviewInput], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };